### ISSUE TITLE
fork / following / .travis.yml / ...

### ISSUE THREAD

**Issue by andete** [Orangenosecom/philipshue#16]
Hey,

I forked your repo as I wanted to publish a newer version of the library, but it looks like you're active in this repo again, so I'm happy to withdraw my "philips_hue_client" from crates.io and use your version. I'd rename my repo to match yours and just follow along. (And maybe a pull request in the future...)

There's one thing that is bugging me though and that is the .travis.yml files and similar. It seems like they are entirely user-specific, yet they will create merge conflicts if we both keep our own configuration for it...

Any idea how that usually is handled ?

Cheers, Joost

**Comment by LFalch** [comment]
I don't think people normally test forks on Travis since they are very user-specific. I'm not sure whether there is a good way to handle that.

Also I'd happily accept PRs if add any features/fix bugs.

**Comment by andete** [comment]
Thanks!
