### ISSUE TITLE
Use UPnP for discovering bridges instead

### ISSUE THREAD

**Issue by LFalch** [Orangenosecom/philipshue#5]
This would remove the dependency for SSL.

**Comment by gugi9000** [comment]
Isn't this fixed by https://github.com/Orangenosecom/philipshue/commit/f0a1d61f0f4202c586c35f5b384d25765f666aa1 ?

**Comment by LFalch** [comment]
@gugi9000 Yes, but it hasn't been merged.

**Comment by LFalch** [comment]
f0a1d61 doesn't replace the current discovery method either, it just adds UPnP, which is not what this issue is about

**Comment by LFalch** [comment]
¯\_(ツ)_/¯
